name: Run Python Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Run poetry install
        run: pip install pytest

      - name: Run tests
        run: python -m pytest